export const CHATBOT_SUGGESTIONS = [
  "Tum projeler ozet",
  "Diplomasi360 aktif katilimci sayisi",
  "KADEME+ katilimci listesi limit 50",
  "Pergel program listesi son 30 gun",
  "Eurodesk basvuru ozeti son 30 gun",
  "KPD ozel modul ozeti",
  "Diplomasi360 dijital bohca listesi",
  "Pergel odev ozeti",
  "KADEME+ sertifika listesi",
  "Egitmen ozeti",
  "Log ozeti son 7 gun",
  "Destek ozeti",
  "Talep listesi son 30 gun",
  "Duyuru listesi",
  "Kullanici rol dagilimi",
  "Action scope mantigi",
  "Yardim",
];