export const CHATBOT_SUGGESTIONS = [
  "Tüm projeler özet",
  "Diplomasi360 aktif katılımcı sayısı",
  "KADEME+ katılımcı listesi limit 50",
  "Pergel program listesi son 30 gün",
  "Eurodesk başvuru özeti son 30 gün",
  "KPD özel modül özeti",
  "Diplomasi360 dijital bohça listesi",
  "Pergel ödev özeti",
  "KADEME+ sertifika listesi",
  "Eğitmen özeti",
  "Log özeti son 7 gün",
  "Destek özeti",
  "Talep listesi son 30 gün",
  "Duyuru listesi",
  "Kullanıcı rol dağılımı",
  "Action scope mantığı",
  "Yardım",
];